<?php
use Magento\Catalog\Model\Product as P;
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>
<div
	class='df-hidden julio-video <?= $block->getNameInLayout()?>'
	data-video="<?= $block->escapeHtml(df_product_current()['julio__video']) ?>"
>
	<div>
		<a href='javascript:void(0)'>
			<div>
				<div class='jul-inactive'></div>
				<div class='jul-active'></div>
			</div>
			<span>Video</span>
		</a>
	</div>
</div>
<?= df_js_x('div.julio-video', 'Julio_Video');