<?php
use Magento\Catalog\Model\Product as P;
use Magento\Framework\View\Element\Template;
	/** @var Template $block */
	$p = df_product_current(); /** @var P $p */
	$v = $p['julio__video'];
?>
<div class='julio-video <?= $block->getNameInLayout()?>'>
	<div>
		<a href='javascript:void(0)'>
			<div>
				<div class='jul-inactive'></div>
				<div class='jul-active'></div>
			</div>
			<span>Video</span>
		</a>
	</div>
</div>
<?= df_js_x('.julio-video', 'Julio_Video');